#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "aalda.docker-registry", "1.0.3"
role "DavidWittman.redis", "1.0.3"
role "docker_server", path: "./roles-static/docker_server"
role "gandalf", path: "./roles-static/gandalf"
role "greendayonfire.mongodb", "1.2.1"
role "hipache", path: "./roles-static/hipache"
role "tsuru_api", path: "./roles-static/tsuru_api"
