#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "aalda.docker-registry", "1.0.4"
role "greendayonfire.mongodb", "1.2.1", github: "UnderGreen/ansible-role-mongodb"

# Playbooks that are not currently in ansible-galaxy
role "docker_server", path: "./roles-static/docker_server"
role "gandalf", path: "./roles-static/gandalf"
role "hipache", path: "./roles-static/hipache"
role "tsuru_api", path: "./roles-static/tsuru_api"
role "bennojoy.redis", path: "./roles-static/bennojoy.redis"
